version: '3.8'

services:
  postgres:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: thebank
      POSTGRES_PASSWORD: 1234567890
    ports:
      - "5432:5432"
    networks:
      - bank_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    volumes:
      - "C:/Users/User/Documents/DockerVolumes/pgadmin:/var/lib/pgadmin"
    depends_on:
      - postgres
    networks:
      - bank_network

  camunda_bpm_0:
    build: 
      context: .
      dockerfile: Dockerfile.springsessionjdbc
    expose:
      - "8080"
    depends_on:
      - redis
      - postgres
    networks:
      - bank_network
  camunda_bpm_1:
    build:
      context: .
      dockerfile: Dockerfile.springsessionjdbc
    expose: 
      - "8080"
    depends_on:
      - redis
      - postgres
    networks:
      - bank_network

  redis:
    image: redis:3.2-alpine
    networks:
      - bank_network

  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - camunda_bpm_0
      - camunda_bpm_1
    ports:
      - "80:80"
    networks:
      - bank_network

networks:
  bank_network:
    driver: bridge