server:
  port: 8080

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  authorization:
    enabled: true
  default-serialization-format: application/json
  history-level: full

datasource.business:
  driverClassName: org.postgresql.Driver
  jdbc-url: jdbc:postgresql://host.docker.internal:5432/business
  username: thebank
  password: 1234567890
  hibernate:
    hbm2ddl.auto: create
    dialect: org.hibernate.dialect.PostgreSQLDialect

datasource.camunda:
  driverClassName: org.postgresql.Driver
  jdbc-url: jdbc:postgresql://host.docker.internal:5432/camunda
  username: thebank
  password: 1234567890

datasource.session:
  driverClassName: org.postgresql.Driver
  jdbc-url: jdbc:postgresql://host.docker.internal:5432/session
  username: thebank
  password: 1234567890

spring:
  jpa:
    open-in-view: false
  session:
    store-type: jdbc