server:
  port: 8080

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  authorization:
    enabled: true
  default-serialization-format: application/json
  history-level: full

datasource.camunda:
  driverClassName: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://172.23.96.1:5432/camunda
  username: thebank
  password: 1234567890

datasource.session:
  driverClassName: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://172.23.96.1:5432/session
  username: thebank
  password: 1234567890
